/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "primary": "#004ac6",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        "on-secondary-fixed-variant": "#2f2ebe",
        "outline": "#737686",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-surface-variant": "#434655",
        "on-secondary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#001f26",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#00788c",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "outline-variant": "#c3c6d7",
        "surface-bright": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#d7f6ff",
        "on-secondary-container": "#fffbff",
        "secondary": "#4648d4",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "secondary-container": "#6063ee",
        "on-secondary-fixed": "#07006c",
        "on-error": "#ffffff",
        "primary-container": "#2563eb",
        "secondary-fixed": "#e1e0ff",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "tertiary": "#005e6e",
        "on-primary-fixed": "#00174b",
        "tertiary-fixed": "#acedff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "2rem",
        "container-max": "1600px",
        "unit": "4px",
        "margin-tablet": "1.5rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "table-data": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-mono": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "table-data": ["12px", { "lineHeight": "16px", "fontWeight": "450" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
